# (PART\*) Policies {-}


# Policy Overview

In this section, I provide specific language for all my course policies. These policies are in addition to those policies and procedures outlined in the unversity [bulletin](https://bulletin.wfu.edu). There are slight differences between the [undergraduate college](https://bulletin.wfu.edu/undergraduate/) and the [graduate school](https://bulletin.wfu.edu/graduate/). 



## Tentative Class Schedule

This syllabus is intended to give the student guidance in what may be covered during the semester and will be followed as closely as possible. 
Dates for tests and assignments won't change, barring extraordinary events. 
However, I reserve the right to modify, supplement, and make changes as the course needs arise. 
I try to avoid changes to the syllabus. 
Nevertheless, if changes occur, I will only make changes that are less burdensome and more advantageous to the students. 
(If I make a change that increases your burden, please talk to me so that we can find a solution.)
