```{r,echo=FALSE}
gracewindow <- "36 hours"
```

# Class Engagement

In previous semesters, I maintained a deliberately hard-line attendance policy. However, in light of ongoing public health concerns and my philosophy of treating students as junior colleagues, I've revised this approach. <!-- (It also does not align with my goal of making it through the pandemic without getting COVID... yay, high risk of complications) -->

Class engagement points encourage your active participation with the course material. Specific engagement instructions are available on the class website. You'll receive full credit for meaningful, intentional, and professional engagement with the material and your peers. Remember, you're responsible for any assignments and announcements made during class, even if you're absent.

## Life Happens

As a reasonable and empathetic human, I recognize that life happens. There will be times when your outside-life conflicts with scheduled class events. These life events can be the obvious things (sports, religious holidays, illness, interviews, etc.), but they can also be the less obvious things (spending the entire night looking for your lost pet). My approach is to work with you, but communication is key. You need to let me know *ahead* of time. You don't need to disclose personal details – your privacy matters
. These late policies value discussion and communication over deductions and punishment. 

It is difficult for me, as an instructor, to know your situation and reason for lateness (e.g. are you sick? did you lose WiFi? struggling with mental health? or just forgot?). Without communication, I will assume that you are choosing not to submit work and do not plan on submitting work. An email will help me better understand your needs and focus on coursework. I am more than happy to give extensions and accommodations, so don't be afraid to email me. 


##  Extensions, Absences, Incompletes

### Excused absences

Except in *true* emergencies, discuss potential excused absences with me as far in advance as possible. This discussion *must* occur beforehand. Don't assume an absence will be automatically excused -- but you may assume that I am a reasonable, empathetic person. Document all discussions about absences via email, even if we also talk in person. Unexcused absences will result in a zero for any graded work that should have been performed for or during the missed class. 


### Late Work

+ Be sure to pay close attention to deadlines.  Each assignment typically has two deadlines in Canvas:
  - Recommended Deadline: Usually Friday at 6:00 PM
  - Final Deadline: Usually end of Monday (11:59 PM)
+ Submissions are accepted without penalty until the Final Deadline.
+ If you miss the Final Deadline:
  - Email me within *within `r gracewindow`* of the missed Final Deadline.
  - Explain your situation in as much detail as you feel comfortable with.
  - Provide a proposed new deadline or explicitly ask for an alternative deadline. 
  - If you communicate *within `r gracewindow`* window, I will do my best to work with you to find a solution that allows you to earn full credit.
- Any agreed-upon modifications or new deadlines must be confirmed in writing and apply only to the specific assignment discussed.
- This late policy does not apply to exams or tests.
- If no contact is made within *within `r gracewindow`* of the missed Final Deadline, the assignment will receive a 0 and cannot be made up.
- Alternative deadlines are typically within one week of the original Final Deadline. Exceptions are at my discretion and are rare.
Communicating in advance about potential delays is always appreciated and will generally result in more flexible accommodations.
- In general, I am much more sympathetic and accommodating if you let me know beforehand.

#### Submissions

It's your responsibility to ensure that I receive your assignment by the established deadline and that the submitted version is complete and correct. Unless otherwise specified, all work must be submitted through Canvas (or GitHub if that is the LMS).

Unless you have communicated with me in advance, there will be no makeup tests or exams.

### Incomplete Grades

The incomplete grade policy is set by the university, not by me. However, I must abide by it:

Although the language surrounding incomplete grades differs slightly across the bulletins ( [undergraduate](https://bulletin.wfu.edu/undergraduate/procedures/exams-grading/#:~:text=Incomplete%20Grade); [graduate](https://bulletin.wfu.edu/graduate/procedures/grading/#:~:text=Grade%20of%20I)), and office of [academic advising]( https://advising.wfu.edu/academic-challenges/incompletes/), the intent is consistent. 
Incompletes can only be granted IF a student fails to complete the work of a course because of something outside of the student's control, such as an illness, emergency, or extenuating circumstances. The window to complete the work is narrow, typically 30 days into the next semester. If the work is not completed after that point, the grade is automatically changed to an F. 
