# 310: Methods in Psychological Research {-#statsminor}

```{r setup, include=FALSE}
source("scheduler.R")
knitr::opts_chunk$set(cache=FALSE, dev='pdf')
mon <- as.Date("2022-01-10")
cache=F
number_of_classes=29
number_of_weeks=15

####
#devtools::install_github("crsh/citr")
library(tidyverse)
library(citr)
library(RefManageR)



bib <- ReadBib("book.bib")
bib <- c(bib, as.BibEntry(citation()))
bib[length(bib)]$key = "Rcite"


topic_vjoe=c(
  "Introduction and What is Data Science", 
  "Graphical Data Analysis",
  "Graphical Masterpieces",
  "Scatterplots and Correlations",
  "Quiz 1",
  "Exploratory Data Analysis",#  "Spring Break",#  "",
  "Data Transformations", 
  "Robustness and Resistence", 
  "Replication",
  "Quiz 2",
  "Modern Data Science", 
  "Archival Data", 
  "Data mining and CART",
  "Special Topics",
  "Special Topics" 
  )



topic=c(
  "What is Data Science and Meet the Toolkit", 
  "Data and Visualization",
  "Grammar of data wrangling",
  "Data types and Data Transformations",
  "Tips for effective data visualization",
  "Scientific studies and confounding",#  "Spring Break",#  "",
  "Web scraping", 
  "Functions", 
  "Data and Ethics",
  "Fitting and interpreting models",
  "Prediction and overfitting", 
  "Cross validation", 
  "Quantifying uncertainty",
  "Interactive web apps",
  "Special Topics (like: Text analysis; Machine learning; Bayesian inference)" 
  )



```



## Course Description

Methods in Psychological Research introduces statistics and research design for students minoring in psychology. Prereq: P—PSY 151 (D, QR)

This course is designed to help students develop the conceptual background and practical skills necessary to evaluate the statistics encountered in their coursework and in everyday life. It emphasizes selection, application, and interpretation. Topics to be covered include statistical inference, probability distributions, sampling, hypothesis testing, and correlation. The goal will be to go beyond rote memorization of abstract formulas and for students to develop an appreciation for the critical role that statistics plays in psychological science.

Selected Course Objectives:


### Broad goals for the course:
- 1. To understand the selection, computation, and interpretation of descriptive and inferential
statistics
- 2. To learn how to use and interpret R (R Core Team 2018).


## Required Materials

Wickham and Grolemund's R for Data Science text (http://r4ds.had.co.nz/)




## Course Assignments



<!---
Schedule
-->

## `r advdate(mon, 1, topic)`
<!---
- Monday: First Day of Class / Introduction
- Wednesday: What is personality? (Chapter 1)
- Friday: Research in Personality: Sources of Data (Chapter 2)
-->
## `r advdate(mon, 2, topic)`
<!---
- Monday: NO CLASS MLK Day
- Wednesday: Research Design: Validity (Chapter 2)
- Friday: Research Design: Generalizability (Chapter 2; Short Assignment 1 Handed Out)
-->
##  `r advdate(mon, 3, topic)` 
<!---
- Monday: Personality Assessment (Chapter 3)
- Tuesday: "Last day to add full-term class"
- Wednesday: Evaluation and Ethics (Chapter 3)
- Friday: Person versus Situation (Chapter 4)
-->

##  `r advdate(mon, 4, topic)`
<!---
- Monday: What are traits? What are the basic traits? (Chapter 4)
- Wednesday: Personality Judgement (Chapter 5)
- Friday: Using Personality Traits to Understand Behavior (Chapter 6; Assignment 1 Due)
-->
##  `r advdate(mon, 5, topic)`
<!---
- Monday: Big Five (Chapter 6)
- Wednesday: Review
- Friday: Test 1
-->
##  `r advdate(mon, 6, topic)`
<!---
- Monday: Brains (Chapter 8)
- Wednesday: More Brains (Chapter 8)
- Friday: Behavior Genetics (Chapter 9)
-->
##  `r advdate(mon, 7, topic)` 
<!---
- Monday: Behavior Genetics (Chapter 9)
- Wednesday: Evolutionary Psychology (Chapter 9)
- Friday: Evolutionary Psychology (Chapter 9)
-->
##  `r advdate(mon, 8, topic)`
<!---
- Monday: Personality over the Lifespan (Chapter 7)
- Wednesday: Personality over the Lifespan (Chapter 7)
- Friday: Personality Processes (Chapter 15)
-->
##  `r advdate(mon, 9, topic)`
<!---
- Monday: No Class
- Wednesday: No Class
- Friday: No Class
-->
##  `r advdate(mon, 10, topic)`
<!---
- Monday: Personality Processes (Chapter 15)
- Wednesday: Review
- Friday: Test 2
-->
##  `r advdate(mon, 11, topic)`
<!---
- Monday: The Self (Chapter 16) Last day to drop with a grade of "W"
- Wednesday: The Self (Chapter 16)
- Friday:  Freud (Chapter 10) 
-->
##  `r advdate(mon, 12, topic)`
<!---
- Monday: Freud (Chapter 10)
- Wednesday: Freud (Chapter 10)
- Friday: Neo-Freud (Chapter 11; Assignment 2 Due)
-->
## `r advdate(mon, 13, topic)`
<!---
- Monday:  Neo-Freud (Chapter 11) 
- Wednesday: Positive Psychology
- Friday: Positive Psychology
-->
##  `r advdate(mon, 14, topic)`
<!---
- Monday: Cross-Cultural Psychology
- Wednesday: Cross-Cultural Psychology
- Friday: Cross-Cultural Psychology
-->

##  `r advdate(mon, 15, topic)`
<!---
- Monday: Personality and Physical Health
- Wednesday: Personality and Mental Health
- Friday: Personality Disorders

##  `r advdate(mon, 16, topic)` 

- Monday: Special Topics
- Wednesday: Review; Assignment 3 Due; Last Day of Class

## Final Exam 

- TBD on DEC TBD

# References

-->
