# Frequently Asked Questions

Below you'll find answers to the questions that I get asked the most by students in my classes. I have been asked every single one of these questions.


## Course Questions


### Where can I find when assignments are due?

You can find due dates in the syllabus.




### Where/what are my grades?

You can find it on canvas, under grades. I will not look this grade for you. You are all hard working and problem-solving students. I believe in you!




### Can you calculate my grade for me?

No because I believe in you!

You are capable of calculating a weighted average. You have 100% of the information you need to do so as outlined in the syllabus. You can calculate your grade using a weighted average and the weightings in the syllabus.
If you really really need help with this, try this website: https://thegradecalculator.com/




### Your curve is confusing. Why can't you just tell me my letter grade?

I agree that my curve is a little confusing at first glance.
But, this curve can only help you. It means I can lower the thresholds for letter grades, but not raise them.
Your best approach is to pretend that there is no curve. 




### Can my parents email you about my class performance?
Unless you are legally a minor, I cannot answer your parents questions about this class.




### Should my parents email you about my class performance?
No.




## Online Learning

### How much time should I spend on one class every week?

The time you spend on a class can vary. No two instructors will format their classes exactly the same. In general, each credit hour corresponds to a minimum of 3 hours of student engagement per week for a traditional 15-week course. This time may be spent on discussions, readings, and lectures, study, and research, and assignments.
If you find yourself spending a lot more or a lot less than 9 hours per week on this class, please let me know. That probably means that either you're doing too much or too little.




### How long are the videos?
You can always check how long the module playlist is by using this website https://ytplaylist-len.herokuapp.com/
Each module has about 1 week worth of lectures.




### Why are there so many videos?
I've sliced up the content into smaller chunks. If you want to watch the entire module worth in one sitting, you can use the youtube playlist.


### Why is your speaking style so weird?

I get this comment frequently in course evaluations. It often gets described as going off on tangents or being impossible to understand or skipping words. I hear you. I really do. I cannot help it.

Please, understand that there's not much more I can do at this point. What you are experiencing is the result of years of speech therapy. Trust me -- what you are experiencing is an improvement. If you *genuinely* struggle to understand me, please TALK to me about it. 



### Why is this so much more work compared to face-to-face classes?

It may feel like more work, but it actually isn't. This class covers the same content as the face-to-face version. I have made every effort to not add to your workload. When I have added an assignment in one aspect of the course, I have removed something else from the class.  On average, you should except to spend about 9 hours a week on this class.




### Where can I find more information about technology services or computer resources?
You can find more information here.




### I'm having a trouble with a specific problem, can you fix it for me?
Troubleshooting or problem solving is going to be essential for virtual learning.  Like with anything else related to technology, problems will occur with virtual learning.
Please try basic troubleshooting to fix your problem.
If you still have trouble after troubleshooting, post a the problem to the FAQ and clearly describe what you have already tried.




## Canvas
### How do I use Canvas for Class?

Students will use Canvas to access course content. 
All work/assignments/projects will be distributed and collected through Canvas.




### How do I set my notifications on Canvas for my classes?
You should navigate to your "Account" by pressing the icon in the top-left corner of this page, right under the Canvas Logo. Then you press "Notifications" and will be brought to a screen where you can change and adjust your notifications.




### How do I submit an assignment on Canvas?
Navigate to your assignment and click this button
Double check your work that it's complete and saved correctly. 
Upload or type your work and click submit assignment.




### How do I know when an assignment has been submitted?
After you click "submit assignment," you will see "confetti" on your screen. A notification will appear that looks like this:




### How do I use the Calendar feature in Canvas?
Your calendar will allow you to see assignments and important dates for all of your classes.  
Click this icon to access your calendar 
From here you will see all of your classes on the right side of the page
You can click to see specific class work, or color code your calendar.




### How do I see feedback on my assignments submitted on Canvas?
Log into the course and click on the 'Grades' link.
Find the assignment and click the assignment name.
Click on 'View Feedback' to view all feedback including comments and any additional annotated comments made on the submission.




### How do I accurately check my grades in Canvas?
To get an accurate view of your final grade, make sure to uncheck the Calculate based only on graded assignments checkbox:

 


### How do I contact the Canvas Help Desk?
You can search the Canvas Guides or contact the Canvas Support Helpline by clicking the Help icon (circle with a question mark) in the Account menu.




### Still have questions? 

Post them in the Discussion Board! I can nearly guarantee that somebody else wants to know the answer to your question.

