## "A" Contract

To contract for an "A" in this course, you agree to:

- Earn "Satisfactory" on all in-class assignments save two.

- Miss no more than two classes.

- Exceed expectations regarding in-class device use.

- Produce at least 10 "Satisfactory" portfolio pieces over the course of the semester. 

- Complete all 15 weeks of engagement activities on a schedule you will specify in your contract. 

- Complete two "Satisfactory" Unessays on a schedule you will specify in your contract and present the strongest in class on December 4.


# "B" Contract
To contract for an "B" in this course, you agree to:

- Earn "Satisfactory" on all in-class assignments save three

- Miss no more than three classes.

- Fully meet expectations regarding in-class device use.

- Produce at least 10 "Satisfactory" portfolio pieces over the course of the semester. 

- Complete at least 12 weeks of engagement activities on a schedule you will specify in your contract. 

- Complete one "Satisfactory" Unessay on a schedule you will specify in your contract and present it in class on December 4.


# "C" Contract

To contract for an "C" in this course, you agree to:

Earn "Satisfactory" on all class preparation assignments save four.
Miss no more than three classes.
Take no more than two information overload days during the semester.
Generally meet expectation regarding in-class device according to the policies outlined in the device use rubric.
Write at least six "Satisfactory" lab reports over the course of the semester. As specified in the assignment, lab reports are due within one week of the pertinent laboratory activity.
Complete one "Satisfactory" Unessay on a schedule you will specify in your contract, which you may choose to present or not in class on December 4.
"D" and "F" Grades

