In this course, you will determine the grade you receive by fulfilling a contract you will submit for my approval on <Friday, September 13th>.

Your written contract will detail:

- The requirements you will meet in order to receive the grade for which you've contracted, 

- the penalties you will incur for not meeting those requirements,

- a calendar you will follow for meeting the requirements you have outlined. 

Many aspects of this calendar will be determined by windows outlined on the course schedule, but your contract will take ownership of these deadlines while committing to specific due dates for the course’s more flexible assignments.


Why Contract Grading?
As you no doubt know, grading can be a contentious issue in college courses, particularly in writing- and discussion-based courses, where grades can seem arbitrary and contestable. Grading in school does not much resemble the way you will be evaluated in your lives or careers, where you will define many of your own goals and be measured by how responsibly and effectively you achieve them. To quote Cathy Davidson, a professor at CUNY from whom most of my ideas about contract grading are adapted:

The advantage of contract grading is that you, the student, decide how much work you wish to do this semester; if you complete that work on time and satisfactorily, you will receive the grade for which you contracted. This means planning ahead, thinking about all of your obligations and responsibilities this semester and also determining what grade you want or need in this course. The advantage of contract grading to the professor is no whining, no special pleading, on the students part. If you complete the work you contracted for, you get the grade. Done. I respect the student who only needs a C, who has other obligations that preclude doing all of the requirements to earn an A in the course, and who contracts for the C and carries out the contract perfectly. (This is another one of those major life skills: taking responsibility for your own workflow.)

Contract Details

To fulfill any grade contract a student must do the following, which should nonetheless be specified in the contract submitted for approval. When writing self-assessments students must describe how they have met these requirements in addition to the grade-specific requirements:

Come to class prepared to discuss any assigned readings, videos, or other media. Participate actively in class activities and discussions, making observations and asking questions that help the class think together.

Meet with me in person—during office hours or another scheduled time—at least once around midterm—roughly between weeks 5-8 to ensure you are on-track to meet your contract requirements, discuss any questions or concerns you have about the course or your progress, and decide on any necessary contract amendments.

Contribute significantly to a detailed, inventive Dead Media Poster presentation on October 30th.

Revise contractual assignments as necessary until both you and I consider them "Satisfactory."

Complete a final self-assessment demonstrating that your work has met the agreed requirements, submitting it to Professor Cordell by 5pm on Monday, December 9.

# "A" Contract

To contract for an “A” in this course, you agree to:

Earn "Satisfactory" on all in-class assignments save two.

Miss no more than two classes.

Exceed expectations regarding in-class device according to the policies outlined in the device use rubric.

Produce at least 10 "Satisfactory" portfolio pieces over the course of the semester. 



As specified in the assignment, lab reports are due within one week of the pertinent laboratory activity.

Complete two "Satisfactory" Unessays on a schedule you will specify in your contract and present the strongest in class on December 4.

Complete 
“B” Contract
To contract for an “B” in this course, you agree to:

Earn “Satisfactory” on all class preparation assignments save three.
Miss no more than three classes.
Take no more than one information overload day during the semester.
Fully meet expectations expectations regarding in-class device according to the policies outlined in the device use rubric.
Write at least eight “Satisfactory” lab reports over the course of the semester. As specified in the assignment, lab reports are due within one week of the pertinent laboratory activity.
Complete one “Satisfactory” Unessay on a schedule you will specify in your contract and present it in class on December 4.
“C” Contract
To contract for an “C” in this course, you agree to:

Earn “Satisfactory” on all class preparation assignments save four.
Miss no more than three classes.
Take no more than two information overload days during the semester.
Generally meet expectation regarding in-class device according to the policies outlined in the device use rubric.
Write at least six “Satisfactory” lab reports over the course of the semester. As specified in the assignment, lab reports are due within one week of the pertinent laboratory activity.
Complete one “Satisfactory” Unessay on a schedule you will specify in your contract, which you may choose to present or not in class on December 4.
“D” and “F” Grades
I’ve borrowed this clause, too, from Cathy Davidson, because I cannot improve upon it:

The professor reserves the right to award a grade of D or F to anyone who fails to meet a contractual obligation in a systematic way. A “D” grade denotes some minimal fulfilling of the contract. An “F” is absence of enough satisfactory work, as contracted, to warrant passing of the course. Both a “D” and “F” denote a breakdown of the contractual relationship implied by signing any of the contracts described above.

What About Exceptional (or Mediocre) Work?
I also reserve the right to reward exceptional work throughout the semester using the full range of Northeastern’s grading scale. If you contract for a “B,” for instance, and submit particularly strong pieces to fulfill that contract, I may elect to raise your contracted grade to a “B+.”

Likewise, if you consistently submit mediocre work in fulfillment of your contract, I reserve the right to adjust your grade one half-step down (e.g. from “A” to “A-“) or even, in extreme cases, a full step.

Contract Adjustments
Periodically during the semester I will ask you to evaluate your work thus far and compare it against what you agreed in your grade contract. In these moments you can also take the opportunity to request an adjustment to your contract in either direction. If you find that you will be unable to meet the obligations of your contract, you may request to move to the next lowest grade and its requirements. Contrariwise, if you find that you’ve been performing above the obligations of your contract, you may request to fulfill the requirements for the next higher grade. Important Note: In order to effectively evaluate your own progress, you must keep track of your work, including days missed, IO days taken, blogs completed, and so forth.