To do well in the course, you should read the assigned material before class and re-read previously assigned material as the course progresses. By reading the text before class you will be better prepared to ask questions and integrate the content of lectures with what was presented in the text. For synchronous classes, be sure to attend all lectures and arrive on time. For asynchronous classes be sure to watch all the video lectures and don't leave them until the last minute. Each topic builds directly on the previous one. Thus, if you miss one lecture, you run the risk of being completely lost in the next lecture.

In addition, many professors have implicit (*i.e.*, unspoken) expectations for college classes. I'm going to explicitly state some of those unspoken expectations. I suspect that your other professors have similar expectations -- so this information will help you in your other classes.

- Read the syllabus.
- Read all the class announcements.
- Read the FAQ and post your questions about the class there.
- Read and follow the instructions for each assignment. 
- Read your professor's comments on your submissions -- especially if you did not get full credit on that submission.
- Treat canvas messages like email.
- Read and respond to canvas messages from your professor. 
- Before you send email your professor, try to answer the question yourself by looking at the syllabus, reading the course FAQ, and reading the assignment instructions.
- Know when assignment deadlines are.
- If you need additional time or flexibility on an assignment, you communicate with your professor before the deadline passes.

# Important Information for College and This Course:

Asynchronous courses put a lot of the onus on YOU to keep up with the work. You are not guaranteed any reminders throughout the semester. Go to the schedule included here and put it in your calendar. You are adults and should keep up with your own calendar. You should also 1) check course announcements on Canvas often, and 2) check your email tied to Canvas often. This is how I communicate with you, and I will not continually repeat myself in emails after I have already posted or sent the information.

It is important for you to understand that high school and college are very different. In high school, you may have been permitted to turn in work as late as you like, to redo assignments or quizzes until you were satisfied, and to complete extra credit work. This is not the case in this college-level course. There are no late assignments, make up work, redoing of assignments, or extra credit. These are course policies; they are not opportunities for negotiation. Any requests for such will be ignored unless there is a documentable extenuating emergency. In this case, you should first contact Student Services for assistance, then you may contact me about how to address it in this course. The email from Student Services will tell me not to ignore your request.

There is also a prevalent attitude of, “it doesn’t hurt to ask.” Yes, it does. If I have already made clear my policies and expectations, asking me to violate them damages your credibility as a student. One day you may ask for something that is truly reasonable given an emergency situation, but by then your reputation will precede you. Do not be “the boy who cried wolf;” it is not a respected position.

Finally, you should understand that college is not a fee-for-service arrangement. You are not paying me. You are paying tuition to a University for all kinds of things, very little of which actually “pays my salary.” Salaries are more commonly paid out of government funds, including grants. You start with a zero in college courses and earn your points from there. I am not “giving” you grades or “taking away” points. You have nothing to begin with and build your own score based on what you do and how well you do it (not simply on effort). What I offer you is an opportunity for education, not a grade.
