## Class Presence and Participation.

In previous semesters, I have had a deliberately hardline attendance policy. In the light of the public health crisis, I have done away with the this policy as it doesn't align with my general philosophy of treating students as junior colleagues.

Class presence and participation points are given to encourage your active engagement with the material. You will be rewarded with a perfect score as long as you engage meaningfully with the material and your peers.


<!---

Although not required, most students send their professor a brief e-mail to explain their absence in advance. Students who repeatedly arrive late to the lecture or recitation will have their Class Participation grade lowered. I reserve the right to fail any student who misses more than five class periods. The student who misses a class meeting is responsible for any assignments and/or announcements made.

-->
## Excused absences and extension policy


As a reasonable and empathetic human, I recognize that life happens. There will be times when your outside life conflicts with scheduled class events. These life events can be any of the obvious things (sports, religious holidays, illness, interviews, etc), but they can also be the less obvious, like spending the entire night looking for your lost pet. My general approach is to work with you. You just need to let me know ahead of time. 
<!---
that occasions arise during the academic year that merit the excused absence of a student from a scheduled class during which a graded exercise is given. Examples include participation in sponsored university activities (e.g., debate team, varsity sports), observance of officially designated religious holidays, serious personal problems (e.g., serious illness, death of a member of the student's family), and matters relating to the student's academic training (e.g., graduate or professional school interviews). Conflicts arising from personal travel plans or social obligations do not qualify as excused absences, unless those commitments were set before this course began. If that is the case, please let me know within the first **two weeks** of class.
-->

Except in the case of true emergencies, a possible excused absence should be discussed with me as far in advance as possible and must occur beforehand. You should not assume that an excused absence will automatically be granted -- but you may assume that I am a reasonable, empathetic person. This discussion should occur via email. If you also discuss your situation verbally, please send a summary of the discussion via email to me.  An unexcused absence will result in a zero for any graded work that should have been performed for or during the missed class. 




## Academic Dishonesty Policy

All work submitted for credit must be the student's own and is subject to the provisions of the Wake Forest Honor Code. Details can be found at the Student Conduct web site:
[studentconduct. wfu.edu/honor-system-wfu](https://studentconduct.wfu.edu/honor-system-wfu/). 

Unless I have explicitly stated otherwise, every assessment is closed to outside resources (including, but not limited to books, notes, phones, people). Ignorance of the honor code and assignment instructions is not an acceptable explanation and/or defense.

It is *ALWAYS* academic dishonesty to share test questions or to work together on tests. And frankly, it is really obvious in Canvas when you work together. I literally wrote a \R program that checks for working together, using a non-parametric statistical method.


Violations of this policy result in a zero for the assignment and possible additional penalties, including a referral to honor council, a ban from all extra-credit assignments, and no longer being able to drop assignments.



## Accommodations Policy

If you are (or become) disabled (in any capacity, permanently, or temporarily), and need accommodations in class, reading, or any other work in this course, please contact me to discuss your specific needs as soon as possible. Under the Americans with Disabilities Act, you are legally entitled to reasonable accommodations for disabilities. I will do everything in my capacity as your Professor to ensure that you receive those accommodations. 

Students who need reasonable accommodations for disabilities also should contact the Learning Assistance Center \& Disability Services [lac.wfu.edu](https://lac.wfu.edu/). These accommodations are not retroactive. Therefore, I strongly encourage you to use those accommodations. You rightfully deserve them, both in the legal, moral, and ethical sense. 


## Communication

You are expected to read every LMS announcement, message, and email; as well as view the media embedded within those communications. Students are expected to check e-mail on a frequent and regular basis in order to stay current with University-related communications, recognizing that certain communications may be time-critical. At minimum, you should be checking your communications within 48 hours. Ignorance of a class communication is not grounds for an excused absence or extension.

## Instructor Availability

Please note that I do not typically check email or answer calls during the hours of 7pm and 7am on weekdays, and I do not check these at all on the weekends in order to devote time to family, rest, and living my life. Messages received during these times will receive attention once I am back online. Otherwise you can expect to receive a response to your message within 24 hours, often much sooner. 

I have given out my cell-phone number, in the case of true emergencies. Please be mindful that I am often asleep at 11:59 PM. 


### Self Advocacy

If you are struggling in this class, please talk to me. Do not assume that I know what is going on in your life. Talk to me and tell me what you need. 

### Grading Questions

Please send any questions about grades in writing via email within two weeks after the assignment is returned. If I erred in scoring or in calculating the grade, I will happily update the record. Otherwise, I will be most receptive toward questions framed in terms of your learning (rather than simply your performance), as research has shown that focusing overly on extrinsic rewards (like grades) is likely to lead to all sorts of outcomes that I don’t wish for you (lower interest in the course material, lower learning, lower enjoyment).

# Public Health in the age of COVID-19

```{r child = './covid.Rmd'}
```

# Classroom Climate

I aim to create a learning environment for my students that supports a diversity of thoughts, perspectives, and experiences, and honors your identities (including race, gender, class, sexuality, religion, ability, political affiliation, etc.) To help accomplish this:

- If you have a name and/or set of pronouns that differ from those that appear in your official records, please let me know!

- If you feel like your performance in the class is being impacted by your experiences outside of class, please don't hesitate to come and talk with me. I want to be a resource for you. 

- I (like many people) am still in the process of learning about diverse perspectives and identities. If something was said in class (by anyone) that made you feel uncomfortable, please talk to me about it. 

## Department Statement
The Psychology Department values, respects, and celebrates the experiences, beliefs, and practices stemming from varied cultures and circumstances (emphasizing, but not limited to, those from historically underrepresented groups), and our deep commitment to diversity, equity, and inclusion plays out through coursework, programming by majors, and research. 



# Tentative Class Schedule

This syllabus is intended to give the student guidance in what may be covered during the semester and will be followed as closely as possible. Dates for tests and assignments won't change, barring extraordinary events. However, I reserve the right to modify, supplement and make changes as the course needs arise. I try to avoid changes to the syllabus. Nevertheless, if changes occur, they will always be advantageous to the students.

