# CLASS RECORDING NOTICE

a. Recording of Class Sessions. All or some in-person and synchronous classes may be
recorded. Student images and voices may be captured in these recordings. Recordings will be
available for viewing only by students enrolled in the class via Canvas or an alternative platform.
The recordings are not available for download. No other recording, including by students, is
permitted.

b. Recording Tails in our Synchronous Classes. Synchronous class recordings may include
events that happen before class officially begins or after it officially ends. Students should take
care to not discuss any confidential matters during these periods of time.

c. Access to Recordings. Students may access the class recordings made available to them
solely for the purpose of participating in the course. The recordings may not be used by any
person other than a student enrolled in the course or for any purpose other than to participate in
the course. Students are prohibited from downloading or distributing any portion of the
recordings for any purpose. Students should understand that technical problems or human error
may prevent successful recording.

d. Copyright Notice. Students are advised that Wake Forest University faculty members hold
the copyright in their course materials. The University and the faculty have legal rights in class
recordings.
